export enum TransactionType {
  TRADE = 'TRADE',
  FREE_AGENCY = 'FREE_AGENCY',
  WAIVER_CLAIM = 'WAIVER_CLAIM',
  RELEASED = 'RELEASED',
  WAIVER_CLEAR = 'WAIVER_CLEAR',
  ADMIN_ASSIGN = 'ADMIN_ASSIGN',
  ADMIN_RELEASE = 'ADMIN_RELEASE',
}
